apiVersion: v1
kind: Service
metadata:
  name: QRCode
  namespace: tool
  labels:
    app: QRCode
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
    - name: QRCode
      port: 8081
      targetPort: 8081
      nodePort: 300002
  selector:
    project: ms
    app: QRCode
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: QRCode
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ms
      app: QRCode
  template:
    metadata:
      labels:
        project: ms
        app: QRCode
    spec:
      #当删除Pod时，等待时间
      terminationGracePeriodSeconds: 10
      containers:
        - name: QRCode
          image: tool/QRCode:1.0.00-release
          imagePullPolicy: IfNotPresent
          volumeMounts:
              # 挂载一个空目录用于共享
            - name: logs
              # 容器内目录地址
              mountPath: /app/logs
          ports:
            - protocol: TCP
              containerPort: 8080
          env:
            - name: APP_NAME
              value: QRCode
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              cpu: 1
              memory: 500Mi
#            requests:
#              cpu: 0.5
#              memory: 125Mi
          #就绪探针
          readinessProbe:
            tcpSocket:
              port: 8081
            #延迟加载时间
            initialDelaySeconds: 50
            #重试时间间隔
            periodSeconds: 5
            #超时时间设置
            timeoutSeconds: 10
            #探测失败的重试次数
            failureThreshold: 5
          #存活探针
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
        - name: filebeat
          # 边车有版本要求，所以不加到这里来
#          lifecycle:
#            type: Sidecar
          image: elastic/filebeat:7.9.3
          imagePullPolicy: IfNotPresent
          args:
            - -environment
            - container
            - -c
            - /usr/share/filebeat/config/filebeat.yml
          volumeMounts:
              # 独立的配置文件，这个配置文件通过kubectl create configmap --from-file=path
              # kubectl create -n tool configmap QRCode-filebeat-config --from-file=`pwd`
              # kubectl delete -n tool configmap QRCode-filebeat-config
            - name: filebeat-config
              # 机子内目录
              mountPath: /usr/share/filebeat/config
            - name: logs
              #机子内目录
              mountPath: /app/logs
          resources:
            limits:
              memory: 200Mi
          readinessProbe:
            #使用命令检查
            exec:
              #指令，通过获取是否有锁来判断是否成功
              command:
                #指令
                - cat
                - /usr/share/filebeat/data/filebeat.lock
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/share/filebeat/data/filebeat.lock
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            # 把configMap挂载成机子内的文件，kubectl create configmap --from-file=path
            name: QRCode-filebeat-config
            items:
              - key: filebeat.yml
                path: filebeat.yml
